### ISSUE TITLE
Error after updating to Nuxt 1.1.1

### ISSUE THREAD

**Issue by Slasher154** [samtgarson/nuxt-oauth#6]
Hi,

I recently updated the Nuxt from 1.0.0-rc9 to 1.1.1 and found this error when I ran 'npm run dev' on the terminal

` TypeError: Cannot read property 'authenticated' of undefined
    at __WEBPACK_IMPORTED_MODULE_0__Users_thanatv_WebstormProjects_thaicom_linkbudget_v3_node_modules_babel_runtime_core_js_object_values___default.some (.nuxt/nuxt-oauth.plugin.js:24:0)
    at Array.some (native)
    at __WEBPACK_IMPORTED_MODULE_0__Users_thanatv_WebstormProjects_thaicom_linkbudget_v3_node_modules_babel_runtime_core_js_object_values___default.some (.nuxt/nuxt-oauth.plugin.js:24:0)
    at Array.some (native)
    at matched.some (.nuxt/nuxt-oauth.plugin.js:24:0)
    at Array.some (native)
    at checkAuthenticatedRoute (.nuxt/nuxt-oauth.plugin.js:24:0)
    at module.exports.__WEBPACK_IMPORTED_MODULE_1__nuxt_middleware__.a.auth (.nuxt/nuxt-oauth.plugin.js:29:0)
    at <anonymous> statusCode: 500, name: 'TypeError' }
`

On Google Chrome
![nuxt-oauth-error-16-jan-2017](https://user-images.githubusercontent.com/4638749/34981999-c35b5b20-fadb-11e7-9473-4a9352cce049.png)

The module works fine with the previous Nuxt version.

Thank you.

**Comment by samtgarson** [comment]
I'll look into this when I find some time, PR's are always welcome!

**Comment by Lahori-Jawan** [comment]
I just installed and had the same issue... but @yuki-nakamura commit solved the issu.

**Comment by samtgarson** [comment]
Sweet, @yuki-nakamura if you want to open a PR I’d be happy to merge 👍

**Comment by yuki-nakamura** [comment]
Sorry, @samtgarson.
I just noticed your message.
thank you fix.
